import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class Test3 {
	public static void main(String[] args) throws IOException {
		MyThrowsFile();//这里调用了MyThrowsFile();所以要解决之前抛出的异常，可以将异常再次抛出，这里是main方法
		//调用了我们，所以可以抛给main方法，main再抛给jvm,实际开发中一般最后抛给框架解决
		
	}

	public static void MyThrowsFile() throws IOException {//遇到异常时也可以使用抛出，谁调用谁解决，将异常抛给
		//调用者。
		FileReader reader=null;
		
			reader=new FileReader("E:/a.txt") ;//因为源码中FileReader就是被抛出的，所以使用时需要处理；
			System.out.println("step1");
			char c1=(char)reader.read();
			System.out.println(c1);
			System.out.println("step2");
		} 
		
	
		
	}
